# Generated by Django 2.2.9 on 2020-05-23 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_category', models.IntegerField(blank=True, choices=[(1, '給与所得'), (2, '賞与'), (3, '臨時収入'), (4, 'その他')], null=True, verbose_name='カテゴリー')),
                ('money', models.IntegerField(default=0, verbose_name='金額')),
                ('inday', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入金日')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='品名')),
                ('s_category', models.IntegerField(blank=True, choices=[(1, '食費'), (2, '日用雑貨'), (3, '娯楽'), (4, '交通費'), (5, '光熱費'), (6, 'その他')], null=True, verbose_name='カテゴリー')),
                ('money', models.IntegerField(default=0, verbose_name='金額')),
                ('useday', models.DateTimeField(default=django.utils.timezone.now, verbose_name='使用日')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
            ],
        ),
    ]
