# Generated by Django 2.2.9 on 2020-06-12 07:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '支出カテゴリ',
                'verbose_name_plural': '支出カテゴリ',
                'db_table': 's_category',
            },
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='品名')),
                ('money', models.IntegerField(default=0, verbose_name='金額')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='使用日')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('s_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneybook.S_Category', verbose_name='支出カテゴリ')),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出',
                'db_table': 'spending',
            },
        ),
    ]
